LilReddt/config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    resources :comments, only: [:new, :create, :destroy, :show]
  end
  resources :comments, only: [:new, :create, :destroy, :show]
end

LilReddt/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :user_id, presence: true

  belongs_to :author,
    class_name: :User,
    foreign_key: :user_id

  has_many :post_subs,
    class_name: :PostSub,
    foreign_key: :post_id

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments
end

LilReddt/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      sub_ids = params[:sub_ids]
      sub_ids.each do |sub_id|
        PostSub.create!(post_id: @post.id, sub_id: sub_id)
      end
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.post_sub)
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end
end

LilReddt/app/helpers/posts_helper.rb
module PostsHelper
end

LilReddt/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

LilReddt/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

LilReddt/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<% p_subs = PostSub.where(post_id: @post.id).map{|p_sub| p_sub.sub_} %>

<form action="<%= post_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="patch">

  <label>Title:
      <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  <br>

  <label>URL:
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  <br>

  <label>Body:
    <input type="textarea" name="post[content]" value="<%= @post.content %>">
  </label>
  <br>

  <label>Subs:</label>
  <br>


  <% Sub.all.each do |sub_| %>
    <label>
      <input type="checkbox" name="sub_ids[]" value="<%= sub_.id %>" <%= 'checked' if p_subs.include?(sub_) %> >
      <%= sub_.title %>
    </label>
    <br>

  <% end %>


  <br>

  <input type="submit" name="" value="Edit Post">
</form>

LilReddt/app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%= posts_url %>" method="post">
  <%= auth_token %>

  <label>Title:
      <input type="text" name="post[title]" value="">
  </label>
  <br>

  <label>URL:
    <input type="text" name="post[url]" value="">
  </label>
  <br>

  <label>Body:
    <input type="textarea" name="post[content]" value="">
  </label>
  <br>

  <label>Subs:</label>
  <br>


  <% Sub.all.each do |subs| %>
    <label>
      <input type="checkbox" name="sub_ids[]" value="<%= subs.id %>">
      <%= subs.title %>
    </label>
    <br>

  <% end %>


  <br>

  <input type="submit" name="" value="Create Post">
</form>

LilReddt/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h2> By: <%= @post.author.username %> </h2>

<%= link_to "Edit Post", edit_post_url(@post) %>

<h3>Content</h3>
  <p><%= @post.content %></p>


<h3>Comments</h3>
<%= link_to "Add Comment", "/posts/#{@post.id}/comments/new" %>
<br>
<ul>

<% @post.comments.each do |comment| %>
  <ul>
    <li><%= link_to comment.content, comment_url(comment) %></li>
    <%= comment.comments.each do  %>
  <br>
<% end %>
</ul>

<h3>Subs:</h3>
<ul>
<% @post.post_subs.each do |p_sub| %>
  <li><%= link_to p_sub.sub_.title, sub_url(p_sub.sub_id) %></li>
<% end %>
</ul>

LilReddt/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>