LilReddt/config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    resources :comments, only: [:new, :create, :destroy, :show]
  end
  resources :comments, only: [:new, :create, :destroy, :show]
end

LilReddt/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :string           not null
#  user_id    :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  validates_presence_of :content

  belongs_to :author,
    class_name: :User,
    foreign_key: :user_id

  belongs_to :post
end

LilReddt/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
    render :edit
  end

  def update
  end

  def create
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    comment.post_id = params[:comment][:post_id]
    comment.save
    flash[:errors] = comment.errors.full_messages
    redirect_to post_url(comment.post)
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

LilReddt/app/helpers/comments_helper.rb
module CommentsHelper
end

LilReddt/app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

LilReddt/app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

LilReddt/app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

LilReddt/app/views/comments/new.html.erb
<h1>New Comment</h1>


<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">
  <label>Body
    <input type="textarea" name="comment[content]" value="">
  </label>

  <input type="submit" name="" value="Submit">
</form>

LilReddt/app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>