LilReddt/config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    resources :comments, only: [:new, :create, :destroy, :show]
  end
  resources :comments, only: [:new, :create, :destroy, :show]
end

LilReddt/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :string
#  mod_id      :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, presence: true

  belongs_to :moderator,
    foreign_key: :mod_id,
    class_name: :User

  has_many :sub_posts,
    class_name: :PostSub,
    foreign_key: :sub_id

  has_many :posts,
    through: :post_subs,
    source: :post

end

LilReddt/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: %i(index show)

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = current_user.subs.find(params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.mod_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  private

  def sub_params
    params.require(:subs).permit(:title, :description)
  end
end

LilReddt/app/helpers/subs_helper.rb
module SubsHelper
end

LilReddt/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

LilReddt/app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

LilReddt/app/views/subs/edit.html.erb
<h1>Update Sub</h1>

<form  action="<%= sub_url(@sub) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="Patch">

  <label>Name of Sub
    <input type="text" name="subs[title]" value="">
  </label>
  <label>Description
    <input type="textarea" name="subs[description]" value="">
  </label>

  <input type="submit" name="" value="Update Sub">
</form>

LilReddt/app/views/subs/index.html.erb
<h1>Subs on Subs on Subs</h1>
<h5>It's our way</h5>

<ul>
  <% @subs.each do |sub_instance| %>
  <li>
    <%= link_to sub_instance.title, sub_url(sub_instance) %>
  </li>
  <br>
<% end %>
</ul>

<br>
<%= link_to "Add a sub", new_sub_url %>

LilReddt/app/views/subs/new.html.erb
<h1>Create a Sub</h1>

<form  action="<%= subs_url %>" method="post">
  <%= auth_token %>
  <label>Name of Sub
    <input type="text" name="subs[title]" value="">
  </label>
  <label>Description
    <input type="textarea" name="subs[description]" value="">
  </label>

  <input type="submit" name="" value="Create Sub">
</form>

LilReddt/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<h2><%= @sub.description %></h2>

<ul>

<% @sub.sub_posts.each do |sub_post| %>
  <li><%= link_to sub_post.post.title, post_url(sub_post.post) %></li>
<% end %>
</ul>

<%= link_to "Subs", subs_url %>
<br>
<%= link_to "Create Post", new_post_url %>

LilReddt/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>